apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: i97s9fw76-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:67f63c06f895dea5ca60b75b2fe9e0764d50dd2d@sha256:dd470256416847d56ccb37d0be3d7bee4abfe50deffe38549b33fedd5852d78a
          name: container-image
