apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i97s9fw76-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i97s9fw76-python 
  name: i97s9fw76-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i97s9fw76-python 
